language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew
  - zip -r spring-boot-study *
  - mkdir -p deploy
  - mv spring-boot-study.zip deploy/spring-boot-study.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: spring-boot-study-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-util-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: spring-boot-study-build
    key: spring-boot-study.zip
    bundle_type: zip
    application: spring-boot-study
    deployment_group: spring-boot-study-group
    region: ap-northeast-2
    wait-util-deployed: true

notifications:
  email:
    recipients:
      - jigi@jigi.net
